// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:e58df658-4a0d-49d8-b270-6e96e5209fe5',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'reactnativeauth-hosting-mobilehub-1742794406',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dy1csunrc1de2.cloudfront.net',
    'aws_mobile_analytics_app_id': '94b606b4ed194f679e77e9785c24eb7f',
    'aws_project_id': '93fc0158-882e-4d38-960b-b7c832363bc4',
    'aws_project_name': 'react-native-auth',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'reactnativeauth-mobilehub-1742794406',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_YrZnEMrOP',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '25e0ritoh0hljmkdvst7p9ujpi',
}

export default awsmobile;
