# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'auth' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # inherit! :search_paths
    use_frameworks!

    pod 'AWSMobileClient', '~> 2.6.6'
    pod 'AWSFacebookSignIn', '~> 2.6.6'
    pod 'AWSAuthUI', '~> 2.6.6'
    pod 'AWSAutoScaling'
    pod 'AWSCloudWatch'
    pod 'AWSCognito'
    pod 'AWSCognitoIdentityProvider'
    pod 'AWSDynamoDB'
    pod 'AWSEC2'
    pod 'AWSElasticLoadBalancing'
    pod 'AWSIoT'
    pod 'AWSKinesis'
    pod 'AWSLambda'
    pod 'AWSMachineLearning'
    pod 'AWSMobileAnalytics'
    pod 'AWSS3'
    pod 'AWSSES'
    pod 'AWSSimpleDB'
    pod 'AWSSNS'
    pod 'AWSSQS'
#    pod 'FBSDKCoreKit'
#    pod 'FBSDKLoginKit'
#    pod 'FBSDKShareKit'

  # Pods for auth

  # target 'auth-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'authTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'AWSMobileClient', '~> 2.6.6'
    pod 'AWSFacebookSignIn', '~> 2.6.6'
    pod 'AWSAuthUI', '~> 2.6.6'
    pod 'FBSDKLoginKit'

  end

end

target 'auth-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for auth-tvOS

  target 'auth-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
